name: CD
on:
  workflow_dispatch:
    inputs:
      onnxruntime-ref:
        type: string
        description: "ONNX Runtime repository reference, e.g., 'v1.22.2' or 'main'"
        default: "v1.22.2"
      target-preset:
        type: choice
        description: "Select a predefined target"
        required: false
        default: "all"
        options:
          - "all"
          - linux-aarch64-static
          - linux-x86_64-static
          - macos-aarch64-static
          - macos-x86_64-static
          - windows-md-x86_64-static
          # - windows-mt-x86_64-static
          # - emscripten-wasm32
          - ios-aarch64-static
          - ios-simulator-aarch64-static
          - ios-simulator-x86_64-static
          - android-arm64-v8a-static
          - android-armeabi-v7a-static
          - android-x86_64-static
          - android-x86-static
      target-custom:
        type: string
        description: "Custom target filter (overrides preset if specified, supports substring matching)"
        required: false
      buildtype:
        type: choice
        required: true
        default: 'Release'
        options:
          - 'Both'
          - 'Release'
          - 'Debug'
      required-operators-config-base64:
        type: string
        description: "Optional base64-encoded contents of a *.required_operators.config or *.required_operators_and_types.config file."
        required: false
        default: ""
      enable-reduced-operator-type-support:
        type: boolean
        description: "Enable ONNX Runtime reduced operator type support. Requires required-operators-config-base64."
        required: false
        default: false
      publish:
        type: boolean
        description: "Publish as draft release on GitHub."
        required: false
        default: false

jobs:
  build-debug:
    if: inputs.buildtype == 'Both' || inputs.buildtype == 'Debug'
    uses: ./.github/workflows/_build.yml
    with:
      onnxruntime-ref: ${{ inputs.onnxruntime-ref }}
      buildtype: Debug
      target-preset: ${{ inputs.target-preset }}
      target-custom: ${{ inputs.target-custom }}
      required-operators-config-base64: ${{ inputs.required-operators-config-base64 }}
      enable-reduced-operator-type-support: ${{ inputs.enable-reduced-operator-type-support }}

  build-release:
    if: inputs.buildtype == 'Both' || inputs.buildtype == 'Release'
    uses: ./.github/workflows/_build.yml
    with:
      onnxruntime-ref: ${{ inputs.onnxruntime-ref }}
      buildtype: Release
      target-preset: ${{ inputs.target-preset }}
      target-custom: ${{ inputs.target-custom }}
      required-operators-config-base64: ${{ inputs.required-operators-config-base64 }}
      enable-reduced-operator-type-support: ${{ inputs.enable-reduced-operator-type-support }}

  publish:
    if: inputs.publish && always() && !cancelled() && !contains(needs.*.result, 'failure')
    needs: [build-debug, build-release]
    uses: ./.github/workflows/_publish.yml
    with:
      onnxruntime-ref: ${{ inputs.onnxruntime-ref }}
